### ISSUE TITLE
Add formatting option for whitespace

### ISSUE THREAD

**Issue by senyai** [RedCMD/TmLanguage-Syntax-Highlighter#11]
Formatting adds these three wihitespaces that I personally don't like:

```
"3": { "name": "punctuation.definition.markdown" },
      ^                                         ^ ws
"fileTypes": [ ],
              ^ ws
```
Maybe add a configuration option `"whitespaceInsideBrackts": {"type": "boolean"}`? I can make a PR, if you like.

**Comment by RedCMD** [comment]
Good idea

PR would be welcomed.
even if it was just the `configuration` side of it
I could do the `format` part of it if need be

at some point, I would like to overhaul the formatter
as it doesn't handle `ERROR`'s very well
format selection is too vague
and it isn't particularly fast either atm

the main files would be [DocumentFormattingEditProvider.ts](https://github.com/RedCMD/TmLanguage-Syntax-Highlighter/blob/main/src/Providers/DocumentFormattingEditProvider.ts), [extension.ts](https://github.com/RedCMD/TmLanguage-Syntax-Highlighter/blob/main/src/extension.ts) and [package.json](https://github.com/RedCMD/TmLanguage-Syntax-Highlighter/blob/main/package.json)

**Comment by senyai** [comment]
@RedCMD speaking about formatting. Is there code style for this project?

**Comment by RedCMD** [comment]
there's no config file atm
that format file is rather out of date compared to everything else (limited semi-colons etc)
