### ISSUE TITLE
`.vsix` must not be included it the repo

### ISSUE THREAD

**Issue by senyai** [RedCMD/TmLanguage-Syntax-Highlighter#13]
It's place is in 'Releases'.

**Comment by RedCMD** [comment]
I need to setup auto publishing releases
and an auto updating changelog

**Comment by RedCMD** [comment]
maybe I can take some notes from https://github.com/harrydowning/yaml-embedded-languages/blob/master/.github/workflows/pipeline.yml

**Comment by RedCMD** [comment]
Annoying github won't allow you to disable `prerelease Releases` notifications without disabling normal `Releases` notifications 
https://github.com/orgs/community/discussions/29192
https://github.com/orgs/community/discussions/4993
