### ISSUE TITLE
[bug]  if has unlength string, format has bug

### ISSUE THREAD

**Issue by CoffeeChaton** [RedCMD/TmLanguage-Syntax-Highlighter#14]
https://github.com/RedCMD/TmLanguage-Syntax-Highlighter/assets/63182963/b92784b0-8ef5-47f3-b284-f6b3d88bcd05

https://github.com/RedCMD/TmLanguage-Syntax-Highlighter/assets/63182963/099e9b84-1f91-407f-a263-c31934beca0f

```json
{
    "information_for_contributors": [ 
        "if has unlength string, format has bug, exp:last line",
        ""
    ],
    "fileTypes": [ "ahk" ],
    "name": "AutoHotkey",
    "patterns": [
        {
            "match": "\\n",
            "name": "meta.ending-space"
        }
    ],
    "scopeName": "source.ahk"
}
```

if has `""` , then format has bug.
If the extension thinks this is a syntax error, please use diagnostics to let me know rather than making the formatting look weird.
thanks~

**Comment by RedCMD** [comment]
if you look up the top in the Breadcrumbs bar
you'll see that TreeSitter has detected it as an `ERROR` for some reason 🐛 

and currently the Formatter doesn't handle `ERROR` very well 🐛

I'll fix tonight

**Comment by RedCMD** [comment]
Already fixed in the latest pre-release
![image](https://github.com/RedCMD/TmLanguage-Syntax-Highlighter/assets/33529441/f985b51c-1ab4-4f43-a081-37dd36a844db)
