### ISSUE TITLE
`\\[` should look like `\\]`

### ISSUE THREAD

**Issue by CoffeeChaton** [RedCMD/TmLanguage-Syntax-Highlighter#15]
![image](https://github.com/RedCMD/TmLanguage-Syntax-Highlighter/assets/63182963/7d86a9d1-42e1-45d6-8b51-306734ad4ced)

| k                   | v                                     |
| ------------------- | ------------------------------------- |
| language            | regex-tmLanguage                      |
| standard token type | Other                                 |
| foreground          | #56B6C2                               |
| background          | #282C34                               |
| contrast ratio      | 5.91                                  |
| textmate scopes     | constant.character.escape.tm          |
| ...                 | meta.embedded.block.regexp.tmLanguage |
| ...                 | source.json.textmate                  |
| foreground          | constant.character.escape             |
| ...                 | { "foreground": "#56B6C2" }           |

![image](https://github.com/RedCMD/TmLanguage-Syntax-Highlighter/assets/63182963/e8ec27b6-e94d-49b5-994c-932e7e595d95)

| k                   | v                                     |
| ------------------- | ------------------------------------- |
| language            | regex-tmLanguage                      |
| standard token type | Other                                 |
| foreground          | #ABB2BF                               |
| background          | #282C34                               |
| contrast ratio      | 6.57                                  |
| textmate scopes     | punctuation.definition.tag.tm         |
| ...                 | meta.embedded.block.regexp.tmLanguage |
| ...                 | source.json.textmate                  |
| foreground          | meta.embedded                         |
| ...                 | { "foreground": "#ABB2BF" }           |

```jsonc
"match": "^[ \\t]*;\\s*\\[\\]"
;                      ^^^ #1
;                          ^^^ #2
```

I think it's a good idea to use the same color, after all, they have the same meaning.
Thanks ≧▽≦

**Comment by RedCMD** [comment]
I original reason for that was because the `\\` isn't needed and is redundant on `]`
`^[ \\t]*;\\s*\\[]` works fine with no errors

I have since learned about the 'dead code' feature
so I'll implement that feature instead soon™️

**Comment by CoffeeChaton** [comment]
you are right, I think I'm confusing the implementation details of js-regexp/oniguruma-regexp,
Usually I translate from js-regexp with u-flag back to onig-regexp.

```jsonc
// onig is OK
"match" : "^[ \\t]*;\\s*\\[]"
```

---

![image](https://github.com/RedCMD/TmLanguage-Syntax-Highlighter/assets/63182963/bce96aae-9092-4678-943e-d5e72494fcd9)

about js-regexp `u` flag

> <https://eslint.org/docs/latest/rules/require-unicode-regexp>
>
> - **Make the regular expression throwing syntax errors early as disabling [Annex B extensions](https://www.ecma-international.org/ecma-262/6.0/#sec-regular-expressions-patterns).**
>
> Because of historical reason, JavaScript regular expressions are tolerant of syntax errors. For example, `/\w{1, 2/` is a syntax error, but JavaScript doesn’t throw the error. It matches strings such as `"a{1, 2"` instead. Such a recovering logic is defined in Annex B.
>
> The `u` flag disables the recovering logic Annex B defined. As a result, you can find errors early. This is similar to [the strict mode](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Strict_mode).
