### ISSUE TITLE
Regex syntax error is not shown

### ISSUE THREAD

**Issue by vanowm** [RedCMD/TmLanguage-Syntax-Highlighter#3]
It doesn't show errors if there is a missing bracket:
```
{
{"test": "blah"
}
```

**Comment by RedCMD** [comment]
I've exhausted all possible error checking using textmate

I'm slowly getting there with tree-sitter in the language server

**Comment by RedCMD** [comment]
If you have `editor.bracketPairColorization.enabled` enabled
it'll show invalid bracket pairs
![image](https://user-images.githubusercontent.com/33529441/194018972-86fa49da-70f4-439c-8bdf-99143cfe0272.png)

**Comment by RedCMD** [comment]
Seems vscode `1.71.2` has problems with not showing erroneous brackets
correct behaviour is shown in 1.70.1
![image](https://user-images.githubusercontent.com/33529441/194241945-d5809fc7-c94c-41fb-ac4e-0a07d2eb812d.png)


What theme are you using?
it seems it doesn't support the scope `invalid`

**Comment by RedCMD** [comment]
Red squiggle errors will be a future feature with tree-sitter in the language server

**Comment by RedCMD** [comment]
https://github.com/microsoft/vscode/issues/198025

**Comment by RedCMD** [comment]
Now available in the full release 2.3.0
