### ISSUE TITLE
Surrounds not working for embedded regex grammar

### ISSUE THREAD

**Issue by DaelonSuzuka** [RedCMD/TmLanguage-Syntax-Highlighter#6]
![Code_Vh47ek903m](https://github.com/RedCMD/TmLanguage-Syntax-Highlighter/assets/18042232/67362ab5-56b8-4416-a1e4-33ad5e3192b3)

Parens and single quotes are listed in `regex.language-configuration.json` as surround pairs, but they're not surrounding in a `tmLanguage.json` file.

I was gonna open a PR adding just parens to the `tmLanguage.json` configuration but it looks like there's a bigger issue with the embedded language's configuration not applying.

**Comment by RedCMD** [comment]
yes, there is problems with vscode not correctly applying language settings for embedded languages 
there are some bug reports

I'll add parens to the json `language-configuration.json` file tomorrow
is there any others you want added?

**Comment by DaelonSuzuka** [comment]
> yes, there is problems with vscode not correctly applying language settings for embedded languages

Not surprising. I have an embedded language extension too and it's definitely a janky API.

> is there any others you want added?

I think that's it. `regex.language-configuration.json` has single quotes but I can't remember ever wrapping something in single quotes in a regex.

Thanks for the quick response!

**Comment by RedCMD** [comment]
single quotes `'` can be used instead of angle brackets `<>` for named groups and referencing
`(?'name'...) \\g`5` \\k'name' (?(`name')...|...)` etc

**Comment by DaelonSuzuka** [comment]
Thanks!
