### ISSUE TITLE
Change the default style for embedded regex

### ISSUE THREAD

**Issue by dragon-archer** [RedCMD/TmLanguage-Syntax-Highlighter#8]
![image](https://github.com/RedCMD/TmLanguage-Syntax-Highlighter/assets/45531248/8058606b-2f99-4700-828a-ad823e186dd2)

As shown in the picture, the default style is `markup.italic`, however, it makes distinguish `|` and `/` hard (especially if they're not adjacent)

How about change the style to `bold` or simply remove the `italic`?

**Comment by RedCMD** [comment]
I've simply just removed the `italic`
as I want character class literals to look ever so slightly different to `normal` literals (which are bold)

**Comment by dragon-archer** [comment]
Fine, it works.
